[package]
name = "MTCGAGA"
version = "0.1.6"
edition = "2024"

[dependencies]
xcap = "0.8.0"
axum = "0.8.7"
device_query = "4.0.1"
rdev = "0.5.3"
enigo = "0.6.1"
shlex = "1.3.0"
serde = "1.0.228"
image = { version = "0.25.9", features = ["bmp"] }
tokio = { version = "1.48.0", features = ["full"] }